---
deployment:
  tasks:
    - export DEPLOYPATH=/home/festival/public_html/goodlife.pe/web-new
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    